apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-analysis-step
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-analysis-step
  template:
    metadata:
      labels:
        app: rollout-analysis-step
    spec:
      containers:
      - name: rollouts-demo
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        lifecycle:
          preStop:
            httpPost:
              path: /traffic/off
              port: 8080
            # exec:
            #   command: ["/bin/sh", "-c", "curl -X POST http://localhost:8080/traffic/off && echo OK || echo Failed"]
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.ready }}
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.live }}
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
  strategy:
    canary:
      # maxSurge: 1
      # maxUnavailable: 0
      steps:
      - setWeight: 30
      - pause: { duration: 30s }
      - setWeight: 60
      - pause: { duration: 30s }
      - setWeight: 100
      - pause: { duration: 10s }
      - analysis:
          args:
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: latest-hash
            valueFrom:
              podTemplateHashValue: Latest
          templates:
          - templateName: pass
